
openapi: 3.0.0
info:
  title: API Генерации Рациона
  version: 1.0.0
  description: |
    API для приложения по созданию персонализированных рационов питания с использованием ИИ.

servers:
  - url: https://example.com/api/v1

paths:
  /user:
    post:
      summary: Создание нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Пользователь создан

  /user/{id}:
    get:
      summary: Получить информацию о пользователе
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      summary: Обновить информацию о пользователе
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Данные обновлены

  /meal-plan/generate:
    post:
      summary: Генерация плана питания
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealPlanRequest'
      responses:
        '200':
          description: Сгенерированный рацион
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'

  /meal-plan/user/{userId}:
    get:
      summary: Получить список рационов пользователя
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список рационов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MealPlan'

  /meal-plan/{planId}:
    get:
      summary: Получить конкретный рацион
      parameters:
        - in: path
          name: planId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Один рацион
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'

    delete:
      summary: Удалить рацион
      parameters:
        - in: path
          name: planId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Удалено

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        age:
          type: integer
        gender:
          type: string
        height:
          type: number
        weight:
          type: number
        goal:
          type: string
        preferences:
          type: array
          items:
            type: string

    MealPlanRequest:
      type: object
      properties:
        age:
          type: integer
        gender:
          type: string
        height:
          type: number
        weight:
          type: number
        goal:
          type: string
        preferences:
          type: array
          items:
            type: string

    MealPlan:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        breakfast:
          type: string
        lunch:
          type: string
        dinner:
          type: string
        snacks:
          type: array
          items:
            type: string
